services:
  - docker

script:
  - docker --version # print the version for logging
  - export TAG=0.1.$TRAVIS_BUILD_NUMBER
  - docker compose -f docker-compose-build.yaml build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push loongluangkhot/udagram-reverseproxy:$TAG
  - docker push loongluangkhot/udagram-api-user:$TAG
  - docker push loongluangkhot/udagram-api-feed:$TAG
  - docker push loongluangkhot/udagram-frontend:$TAG