services:
  - docker

install:
  - docker --version # print the version for logging
  - docker-compose --version # print the version for logging
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export TAG=0.1.$TRAVIS_BUILD_NUMBER
  - echo $TAG
  - docker build -t udagram-api-user:$TAG ./udagram-api-user
  # - docker-compose -f docker-compose-build.yaml build
  # - docker push loongluangkhot/udagram-reverseproxy:$TAG
  # - docker push loongluangkhot/udagram-api-user:$TAG
  # - docker push loongluangkhot/udagram-api-feed:$TAG
  # - docker push loongluangkhot/udagram-frontend:$TAG

script:
  - echo "Build $TAG is successful!"