version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

commands:
  restore-docker-cache:
    steps:
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true

jobs:
  build-udagram-api-feed:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push application Docker image for udagram-api-feed
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/udagram-api-feed:$TAG ./udagram-api-feed
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/udagram-api-feed:$TAG
  build-udagram-api-user:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push application Docker image for udagram-api-user
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/udagram-api-user:$TAG ./udagram-api-user
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/udagram-api-user:$TAG
  build-udagram-frontend:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push application Docker image for udagram-frontend
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/udagram-frontend:$TAG ./udagram-frontend
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/udagram-frontend:$TAG

workflows:
  build-udagram-api-feed:
    jobs:
      - build-udagram-api-feed:
          context:
            - docker
  build-udagram-api-user:
    jobs:
      - build-udagram-api-user:
          context:
            - docker
  build-udagram-frontend:
    jobs:
      - build-udagram-frontend:
          context:
            - docker